version: '3.8'

services:
  mongodb:
    image: mongo:8.2.2
    container_name: betting_analyzer_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: betting_analyzer

  redis:
    image: redis:7-alpine
    container_name: betting_analyzer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: